title:   Aleem Shariff
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have always relied on analysis of numbers as an investor in real estate, and financial markets and towards making decisions for both myself and for the various companies I have worked with.  Data is universal and which professional industry or personal decision we make today confidently does not depend on data?  Would you be confident to make a decision without using data? 
  I'm an investor/analyst based in Toronto, my day-to-day involves analysis of trends and financial markets as well as looking for opportunities for investment.
  I thrive on organizing numbers and raw data into detailed dashboards. I also enjoy developing templates and automating processes to streamline analysis for efficiency.
  <br><br>
  <a href="https://www.linkedin.com/in/aleem-shariff-102465177/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/aleem8803">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/aleemshariff/Portfolio-Aleem-Shariff-c00307cc96b94456a981d9bdefcdc61f">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal 
 
